name: Test

on:
  push:
    branches:
      - main
    paths:
      - '**.js'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - name: Install packages
        run: npm ci
      - name: Test
        run: npm run test
        env:
          SECRET_ACCESS_TOKEN: '123456789' # Fake access token with testing purposes.
